### ISSUE TITLE
ios无法导入文件

### ISSUE THREAD

**Issue by sanstale6** [F-Unction/prpr_ipa#1]
能解决下ios15.6.1使用 ipa企业签名安装无法导入文件的问题吗（）在"用其他应用打开"中并没有phira，游戏自带的没法用

**Comment by F-Unction** [comment]
你是说权限不全？

**Comment by F-Unction** [comment]
请问是否为最新版本

**Comment by sanstale6** [comment]
用的0.1.0

发自我的iPad

在 2023年5月12日，12:21，F_Unction ***@***.***> 写道：

﻿

请问是否为最新版本

**Comment by sanstale6** [comment]
游戏自带的导入点击文件没反应（企业签名的应用貌似都是这个现象），有没有其他办法导入（
发自我的iPad

在 2023年5月12日，12:21，F_Unction ***@***.***> 写道：

﻿

请问是否为最新版本

**Comment by F-Unction** [comment]
本人仅为搬运工，自phira发布后的ipa一直都是官方构建，不是脱壳版，理论上不存在权限问题
建议联系phira开发者mivik和sjfhsjfh

**Comment by F-Unction** [comment]
![2258E694-6E17-46C7-80BA-C06613E7825D](https://github.com/F-Unction/phira_ipa/assets/51352133/a25e3d5a-03ff-4adf-b9c5-ee30653d1055)
